version: "3.3"
services:
  autopilot:
    image: autopilotservicetest:v1
    privileged: true
    command: ["Python3", "AutopilotService.py", "broker.hivemq.com"]
    #command: ["tail", "-f", "/dev/null"]
    networks:
      main:
        ipv4_address: 192.168.288.3
    depends_on:
      - mosquitto
    external_links:
      - mosquitto

  mosquitto:
      image: eclipse-mosquitto:latest
      ports:
        - "1883:1883"
        - "1884:1884"
        - "8000:8000"
      volumes:
        - ./config:/mosquitto/config
        - ./data:/mosquitto/data
        - ./log:/mosquitto/log
      networks:
        main:
          ipv4_address: 192.168.288.2


networks:
  main:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.288.0/20

secrets:
  dockerhub_username:
    external: true
  dockerhub_password:
    external: true
      